### ISSUE TITLE
create and use alpine dind image, pull on boot

### ISSUE THREAD

**Issue by progrium** [progrium/envy#2]
We're using the canonical `jpetazzo/dind` image, but it's based on ubuntu and so it's much bigger than it needs to be. This make the first time experience suck. We should use an image based on the contributed alpine based Dockerfile:
https://github.com/jpetazzo/dind/tree/master/alpine

envy should also pull it on boot, as well as ubuntu, just to get a jump on loading those default base images later.

**Comment by fgrehm** [comment]
I could not find that image on the Docker hub, shall we ask Jérôme to enable an automated build for that or do you prefer to just build the image ourselves?

**Comment by progrium** [comment]
Done in #45
