### ISSUE TITLE
support github personal access tokens for web auth

### ISSUE THREAD

**Issue by progrium** [progrium/envy#22]
Should be able to auth using a personal access token as your username.

**Comment by andyshinn** [comment]
Also to note, this is probably the way for anyone using 2 facter authentication with GitHub (including me) to use Envy.

**Comment by progrium** [comment]
Can you confirm that you can use the github API with a personal access token to bypass 2 factor?

**Comment by andyshinn** [comment]
Actually, I noticed this at the bottom of the personal access tokens page:

> Personal access tokens function like ordinary OAuth access tokens. They can be used instead of a password for Git over HTTPS, or can be used to authenticate to the API over Basic Authentication.

I just tested and the personal access token does work in place of the password already. Is it even worth making it work in place of the username?

**Comment by progrium** [comment]
Boom. Already done. Best features require no code change.
