### ISSUE TITLE
debug environment crash

### ISSUE THREAD

**Issue by jgallen23** [progrium/envy#33]
one of my environments keeps restarting itself while I'm logged in.  Is there any way for me to debug this and see what caused the crash?

**Comment by progrium** [comment]
Your session container is restarting or are you talking about the Docker in
Docker for that environment?

On Thu, Jul 2, 2015 at 3:09 PM, Greg Allen notifications@github.com wrote:

> one of my environments keeps restarting itself while I'm logged in. Is
> there any way for me to debug this and see what caused the crash?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/progrium/envy/issues/33.

## 

Jeff Lindsay
http://progrium.com

**Comment by jgallen23** [comment]
the session container.  The one that looks like: jgallen23.123098123

**Comment by jgallen23** [comment]
actually, I think this is a false alarm.  When I commit, the container restarts itself.  I wasn't quite expecting that, but it makes sense.

**Comment by progrium** [comment]
Yeah all operations create a new container. I don't really believe in stopping/starting containers.
