### ISSUE TITLE
list environments

### ISSUE THREAD

**Issue by jgallen23** [progrium/envy#34]
I'm trying to add support to list environments for the current user and I was thinking of adding an `envy-ls` command here: https://github.com/progrium/envy/blob/master/scripts/enterenv#L54.  I've got it listing out the environments, but it restarts the container on every run.  Any way for me to bypass that?  Also, where is the code to execute that function when something exits with a 128 status?

**Comment by progrium** [comment]
Yeah this is what the envy command was going to be for. Probably going to restructure stuff as well.

**Comment by jgallen23** [comment]
if you want to outline what you are thinking, I can take a stab at a pull request

**Comment by progrium** [comment]
The `0.1.0` branch with a PR into master has some good examples of making commands. This command would be `envy environ ls` and would just like names of directories under the user's `environs` directory. Probably needs to some helpers in util to make it simpler.
