### ISSUE TITLE
Please populate README

### ISSUE THREAD

**Issue by ekristen** [progrium/envy#4]
Can you please populate the README and explain what how and this tool works. Thanks.

**Comment by lgs** [comment]
@ekristen  if you really don't like to read 186 lines of code ([58 really](https://github.com/progrium/envy/blob/master/cmd/envyd.go)), then you can just start from here: [https://vimeo.com/131329120](https://vimeo.com/131329120)

**Comment by defel** [comment]
or, this can just be written into the readme

(I saw the video yesterday, and want to use envy at work now.)

**Comment by progrium** [comment]
see #12
