### ISSUE TITLE
Error response from daemon: client and server don't have same version (client : 1.19, server: 1.18)

### ISSUE THREAD

**Issue by jgallen23** [progrium/envy#40]
after building latest envy, I get this error whenever I'm inside a container and run `docker ps`

It looks like the progrium/dind is running docker 1.6.2.

```
bash-4.3# docker version
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): bc9c64f
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): bc9c64f
OS/Arch (server): linux/amd64
```

**Comment by progrium** [comment]
But envy is using 1.6.1

**Comment by progrium** [comment]
in #45 it's using 1.6.2 since i don't trust 1.7 yet. it also starts dind instances using the same docker binary to ensure compatibility with docker in envy sessions and dind instances.
