### ISSUE TITLE
maybe boot2docker incompat or update to jpetazzo/dind

### ISSUE THREAD

**Issue by leafmulch** [progrium/envy#6]
Just noticed this: https://gist.github.com/leafmulch/77e9bbf8b11643265853

I had this working a couple hours ago, but couldn't install redis-cli as your video demoed, so decided to scrub everything and update boot2docker to 1.7 (it was 1.6.x). Now it's not working at all, but I notice there's been a recent update to jpetazzo/dind and errors in logs of that container:-

docker@boot2docker:~/.ssh$ docker images jpetazzo/dind
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
jpetazzo/dind       latest              f9729f762697        About an hour ago   331.7 MB
docker@boot2docker:~/.ssh$ docker images progrium/envy
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
progrium/envy       latest              39378f2a0bbc        3 days ago          231.3 MB
docker@boot2docker:~/.ssh$ ssh -i github_rsa -p 2222 leafmulch@0.0.0.0
Building environment ...
Connection to 0.0.0.0 closed.
docker@boot2docker:~/.ssh$ docker logs leafmulch.leafmulch
time="2015-06-24T15:30:24.382129945Z" level=warning msg="/!\ DON'T BIND ON ANY IP ADDRESS WITHOUT setting -tlsverify IF YOU DON'T KNOW WHAT YOU'RE DOING /!\"
time="2015-06-24T15:30:24.382430533Z" level=info msg="Listening for HTTP on tcp (0.0.0.0:2375)"
time="2015-06-24T15:30:24.382587402Z" level=info msg="Listening for HTTP on unix (/var/run/docker.sock)"
time="2015-06-24T15:30:24.386267813Z" level=warning msg="Running modprobe bridge nf_nat failed with message: , error: exit status 1"
time="2015-06-24T15:30:24.505171613Z" level=info msg="Loading containers: start."

time="2015-06-24T15:30:24.505776187Z" level=info msg="Loading containers: done."
time="2015-06-24T15:30:24.505853733Z" level=info msg="Daemon has completed initialization"
time="2015-06-24T15:30:24.505879465Z" level=info msg="Docker daemon" commit=0baf609 execdriver=native-0.2 graphdriver=aufs version=1.7.0

**Comment by leafmulch** [comment]
This is down to a corrupt /mnt/data volume. Not sure exactly, but I removed it and restarted and all was good with the world. Hopefully you didn't get around to looking at this!?

**Comment by progrium** [comment]
Yeah, I didn't. Boot2docker has some weird bugs like that inherited by VirtualBox that I seemed to run into slightly more often with this project for some reason.
