### ISSUE TITLE
RFE: 2 step authentication with GitHub

### ISSUE THREAD

**Issue by leafmulch** [progrium/envy#7]
I can't login using the chrome method over port 80, as I use 2 step authentication. It would be nice to see support for this some time in the future. Thanks.

**Comment by progrium** [comment]
Since without 2 step, passing your credentials is less than ideal. Because this isn't a hosted service, OAuth is not so much an option. What do you think about using a personal access token?

**Comment by leafmulch** [comment]
Something like Docker gives out for swarm hosts? So I'd register the envy
container centrally somewhere?

I assume you're actually referring to this:
https://help.github.com/articles/creating-an-access-token-for-command-line-use/

I've not had cause to use it, but I'm sure it'd fulfill the role here.
